export const messageConstants = {
  SERVER_FAIL: `Error occurred, server can't start`,
  INVALID_EMAIL: "Please Enter A Valid E-mail!",
  MiddleWare: {
    SIGN_IN: "Please Sign In!",
  },
  token: {
    TOKEN_REQUIRED: "Refresh Token is required!",
    TOKEN_INVALID: "Refresh token is not valid!",
  },
  login: {
    SIGNIN_ISSUE: "Please make a new signin request",
  },
  userData: {
    USER_EXISTS: "User Data Already Exists",
    USER_DATA: "User Data synced successfully",
    ADMIN_DATA: "Admin User Data synced successfully",
    USER_NOTFOUND: "User is not present in the system",
    UNREGISTRED_USER: "This Email-Id is not registered!",
    INVALID_PASSWORD: "Invalid Password!",
    BEFORE_DELETE_ROLE:
      "This user role is in use, please delete the user first",
  },
  failure: {
    SERVER_FAIL: "Failed to start server:",
    INT_SERVER_ERR: "Internal Server Error",
    UNEXP_ERR: "Unexpected Error Occured",
    DB_CONN_FAIL: "Failed to connect to the database:",
    ADD_RESPONSE_ERR: "Response Submission Failed",
  },
  success: {
    SERVER_RUNNING: `Server is running on port ${process.env.PORT}`,
    ADD_RESPONSE: "Response Submitted Successfully",
  },
  role: {
    ROLE_CREATED: "Role Added Successfully",
    COMPANY_ID: "Company ID is required",
    ROLE_NOT_FOUND: "Role not found",
    ROLE_PERMISSIONS_DELETED: "Role and its permissions deleted successfully",
    ROLE_UPDATE: "Role updated successfully",
    ROLE_EXIST: "Role already exist",
    FAILED_TO_DELETE_ROLE: "Failed to delete the role",
    FAILED_TO_DELETE_MODULE_PERMISSIONS:
      "Failed to delete all permissions associated with the role.",
  },
  inputValidation: {
    COMPANYID_REQUIRED: "Company id is required",
    ROLENAME_REQUIRED: "Role name is required",
    ROLEID_REQUIRED: "Role id is required",
    MODULEID_REQUIRED: "Module id is required",
    USERNAME_REQUIRED: "User name is required",
    PASSWORD_REQUIRED: "Password is required",
    STRING_INVALID: "Invalid Input",
  },
  module: {
    ONE: "1",
    TWO: "2",
    THREE: "3",
    FOUR: "4",
    FIVE: "5",
    SIX: "6",
    SEVEN: "7",
    EIGHT: "8",
    ACCESS_CONTROL: "Access Control Module",
    PROFILE_MODULE: "Profile Module",
    ADMIN_DASHBOARD: "Admin Dashboard",
    HR_DASHBOARD: "HR Dashboard",
    LEAVE_HOLIDAY_POLICY: "Leave & Holiday Policy Module",
    SURVEY: "Survey Module",
    USER_DAHSBOARD: "User Dashboard",
    USER_PROFILE: "User Profile",
    MODULE_CREATION_ERR: "Error While Creating Default Modules",
    GET_MODULE_ERR: "Error In getModuleById From Module Service:",
    GET_ALL_MODULE_ERR: "Error In getAllModules From Module Service:",
    CREATE_MODULE_ERR: "Error In createModule From Module Service:",
  },
  Auth: {
    VALIDATION_ERR: "Error In Token Validation:",
    UNAUTHORIZED: "Unauthorized",
    LOGIN_ERR: "Error During Login:",
    TOKEN_REQ: "Token Required",
    TOKEN_ERR: "Error In VerifyTokenController:",
  },
  moduleController: {
    FETCH_ERR: "Error In getModuleById From Module Controller: ",
    ALL_FETCH_ERR: "Error In getAllModules From Module Controller: ",
  },
  roleController: {
    ROLE_UPDATE_ERR: "Error In updateRole From Role Controller: ",
    ROLE_PERMISSION_FETCH_ERR:
      "Error In getRolePermissions From Role Controller: ",
    DELETE_ROLE_ERR: "Error In deleteRole From Role Controller: ",
    ROLE_FETCH_ERR: "Error In getRolesByCompanyId From Role Controller: ",
    ROLE_CREATE_ERR: "Error In createRole From Role Controller",
  },
  userDetails: {
    SYNC_SUCCESS: "User Details Synced Successfully",
    SYNC_ERR: "Error In UserDetailsSync From User Sync Controller",
  },
  authService: {
    AZURE_LOGIN_FAILED: "Azure login failed",
    ROLE_FETCH_ERR: "Role Not Found",
    TOKEN_ERR: "Error In getToken From Auth Service:",
    NO_TOKEN: "No Token Provided",
    INVALID_TOKEN: "Invalid Token",
    TOKEN_GENERATED: "Token Generated",
    TOKEN_VERIFY_ERR: "Error In verifyTokenAndMatchIds:",
    NO_USER: "No User Found",
    VALIDATED: "Token Verified And IDs Matched",
    VERIFY_ERR: "Error In verifyTokenAndMatchIds From Auth Service:",
  },
  permission: {
    CREATE_PERM_ERR: "Error In createPermission From Permission Service:",
    DELETE_PERM_ERR: "Error In deletePermission From Permission Service:",
    GET_PERM_ERR: "Error In getAllPermissions From Permission Service:",
    FIND_PERM_ERR: "Error In findPermission From Permission Service:",
    UPDATE_PERM_ERR:
      "Error In updateExistingPermission From Permission Service:",
  },
  roleService: {
    CREATE_ROLE_ERR: "Error In createRole From Role Service:",
    GET_ROLE_ERR: "Error In getRolesByCompanyId From Role Service:",
    GET_ROLEID_ERR: "Error In getRoleById From Role Service:",
    DELETE_ROLE_ERR: "Error In deleteRole From Role Service:",
    UPDATE_ROLE_ERR: "Error In updateRole From Role Service:",
  },
  userSync: {
    USER_SYNC_ERR: "Error In UserCreationSync From UserSync Service",
  },
  DB: {
    CONNECT: "Connected To MongoDB",
    DISCONNECT: "Disconnected From MongoDB",
    CONNECT_ERR: "MongoDB Connection Error:",
  },
  Role: {
    DEFAULT_ROLE: "Default User",
    DEFAULT_ROLE_CREATED: "Default User Role Created",
    DEFAULT_ROLE_CREATE_ERR: "Error In Creating Default User Role From Index",
    DEFAULT_ROLE_EXISTS: "Default Role Exists",
  },
};
